@DemoApi_HostAddress = http://localhost:5057

GET {{DemoApi_HostAddress}}/healthCheck
Accept: application/json

###
GET {{DemoApi_HostAddress}}/
Accept: application/json

###
GET {{DemoApi_HostAddress}}/data
Accept: application/json

###
